# site settings
title: LAPACE
subtitle: HOSTEL
email: lavita.bella@msa.hinet.net
description: A Hostel located in Taitung.
baseurl: "/lapace" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address: 中山路119-3號
city:  台東市
country: Taiwan
phone: 0952-136857

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings

facebook_url: https://www.facebook.com/lapacehostel/


# build settings
markdown: kramdown

sass:
  style: compressed
